# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

permalink: /:year/:month/:day/:title/
# permalink: pretty

gems: 
  - jekyll-paginate
  - rouge
# 分页
paginate: 5
highlighter: rouge

title: "可知不可违的个人主页"
description: >- # this means to ignore newlines until "baseurl:"
  做人没有理想，那跟咸鱼有什么区别。

# the subpath of your site, e.g. /blog
baseurl: "" 

# the base hostname & protocol for your site, e.g. http://example.com
url: "https://piaoyidaodi.github.io" 

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# about author
author: 
    name: LiZheng
    nickname: 可知不可违
    introduction: 不会写代码的老中医不是好工程师    
    email: piaoyidaodi@gmail.com
    github:  piaoyidiaodi


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
